### ISSUE TITLE
/ | 배포 후 깃허브 로그인 오류

### ISSUE THREAD

**Issue by FEsunmin** [FEsunmin/outsourcing-project#19]
github 로그인 url 배포 url에 맞게 재설정 필요

![image](https://github.com/FEsunmin/outsourcing-project/assets/165988823/8811f7cf-694e-4202-8cbf-435f0300932a)

**Comment by reeny404** [comment]
https://github.com/FEsunmin/outsourcing-project/pull/20/commits/deef850249c9585ea33cf7f2a16a59fb27616535

**Comment by reeny404** [comment]
수정 중
1) PR : https://github.com/FEsunmin/outsourcing-project/pull/20/commits/deef850249c9585ea33cf7f2a16a59fb27616535
2) vercel 환경 변수 셋팅 ```VITE_APP_BASE_URL = "https://outsourcing-project-two.vercel.app/"```
3) supabase 설정
![image](https://github.com/FEsunmin/outsourcing-project/assets/61840162/b447641f-e168-45c1-82f3-12dd1886295b)

**Comment by reeny404** [comment]
수정 완료
