### ISSUE TITLE
현재 진행중인 경기 | 기획 재고민

### ISSUE THREAD

**Issue by reeny404** [FEsunmin/outsourcing-project#31]
현재 고정으로 들어가있는데, 저기에 보여줄 수 있는 새로운 정보 혹은 환기시킬만한 다른 정보는 없을까?

**Comment by dongkyusq** [comment]
일단 고정으로 넣을거면 "아직 진행중인 경기가 없습니다"라는 코멘트로 수정하거나 
제목을 최근 경기 기록으로라도 바꾸면 괜찮아보이지 않을까합니다.

**Comment by reeny404** [comment]
https://github.com/FEsunmin/outsourcing-project/pull/44 최근경기 기록으로 변경
