### ISSUE TITLE
메인 페이지, 팀순위와 경기 매치에 나오는 팀명 통일하기

### ISSUE THREAD

**Issue by reeny404** [FEsunmin/outsourcing-project#32]
통일하는 김에 표 라인 맞추기
![image](https://github.com/FEsunmin/outsourcing-project/assets/61840162/498a9573-2ff0-4e94-b6e9-f4f89abe2bab)

**Comment by reeny404** [comment]
![image](https://github.com/FEsunmin/outsourcing-project/assets/61840162/255a544b-6548-4cb7-a868-d7c4c4425c49)

**Comment by yeliinbb** [comment]
수정 및 PR 완료
